//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace StockVentas.com.karminna {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TratarImagenesServiceBinding", Namespace="http://karminna.com/soap/TratarImagenesService")]
    public partial class TratarImagenesService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TratarImagenesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarImagenesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TratarImagenesService() {
            this.Url = global::StockVentas.Properties.Settings.Default.StockVentas_com_karminna_TratarImagenesService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TratarImagenesCompletedEventHandler TratarImagenesCompleted;
        
        /// <remarks/>
        public event BorrarImagenesCompletedEventHandler BorrarImagenesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://karminna.com/tratar_imagenes_service.php/TratarImagenes", RequestNamespace="http://localhost/Ecommerce/trunk/public_html/nusoap/lib", ResponseNamespace="http://localhost/Ecommerce/trunk/public_html/nusoap/lib")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string TratarImagenes(string name) {
            object[] results = this.Invoke("TratarImagenes", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TratarImagenesAsync(string name) {
            this.TratarImagenesAsync(name, null);
        }
        
        /// <remarks/>
        public void TratarImagenesAsync(string name, object userState) {
            if ((this.TratarImagenesOperationCompleted == null)) {
                this.TratarImagenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTratarImagenesOperationCompleted);
            }
            this.InvokeAsync("TratarImagenes", new object[] {
                        name}, this.TratarImagenesOperationCompleted, userState);
        }
        
        private void OnTratarImagenesOperationCompleted(object arg) {
            if ((this.TratarImagenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TratarImagenesCompleted(this, new TratarImagenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://karminna.com/tratar_imagenes_service.php/BorrarImagenes", RequestNamespace="http://localhost/Ecommerce/trunk/public_html/nusoap/lib", ResponseNamespace="http://localhost/Ecommerce/trunk/public_html/nusoap/lib")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string BorrarImagenes(string name) {
            object[] results = this.Invoke("BorrarImagenes", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarImagenesAsync(string name) {
            this.BorrarImagenesAsync(name, null);
        }
        
        /// <remarks/>
        public void BorrarImagenesAsync(string name, object userState) {
            if ((this.BorrarImagenesOperationCompleted == null)) {
                this.BorrarImagenesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarImagenesOperationCompleted);
            }
            this.InvokeAsync("BorrarImagenes", new object[] {
                        name}, this.BorrarImagenesOperationCompleted, userState);
        }
        
        private void OnBorrarImagenesOperationCompleted(object arg) {
            if ((this.BorrarImagenesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarImagenesCompleted(this, new BorrarImagenesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TratarImagenesCompletedEventHandler(object sender, TratarImagenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TratarImagenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TratarImagenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BorrarImagenesCompletedEventHandler(object sender, BorrarImagenesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarImagenesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarImagenesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591